import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

import { toast } from "react-toastify";
import CategorySelect from "../shared/components/layouts/appLayout/CategorySelect";
import HomePageSection from "../shared/components/layouts/appLayout/HomePageSection";
import FeedLayout from "../shared/components/layouts/FeedLayout";

const Home: NextPage = () => {
  return (
    // <div>
    //   <Head>
    //     <title>Create Next App</title>
    //     <meta name="description" content="Generated by create next app" />
    //     <link rel="icon" href="/favicon.ico" />
    //   </Head>
    // </div>
    <>
      <HomePageSection />
      <CategorySelect />
      <FeedLayout />
    </>
  );
};

export default Home;
